# Generated by Django 6.0.3 on 2026-03-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'import_batch',
            },
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.importbatch'),
        ),
    ]
